### ISSUE TITLE
testsuite fails to build with ghc-9.6.3

### ISSUE THREAD

**Issue by juhp** [haskell-hvr/ghc-byteorder#1]
```
       /var/stackage/work/unpack-dir/unpacked/ghc-byteorder-4.11.0.0.10-dc135755ee7ab6663b653516137e4f534a8169b1eb37a6906d92bdc64c4b
9ee8/src-test/tests.hs:26:11: error: [GHC-39999]
           • No instance for ‘Eq (Maybe IUT.ByteOrder)’
               arising from a use of ‘L.nub’
           • In the first argument of ‘($)’, namely ‘L.nub’
             In the expression:
               L.nub
                 $ zipWith inferBO octectsLst [beOctets16, beOctets32, beOctets64]
             In a stmt of a 'do' block:
               case
                   (L.nub
                      $ zipWith inferBO octectsLst [beOctets16, beOctets32, beOctets64])
               of
                 [Just x] -> return x
                 _ -> fail ("runtimeByteOrder failed " ++ show octectsLst)
          |
       26 |     case (L.nub $ zipWith inferBO octectsLst [beOctets16,beOctets32,beOctets64]) of
          |           ^^^^^
```

**Comment by andreasabel** [comment]
It does work with cabal:
```
cabal get ghc-byteorder-4.11.0.0.10
cd ghc-byteorder-4.11.0.0.10
cabal test -w ghc-9.6.3
```

Also, `ByteOrder` _does_ have an `Eq` implementation: https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-ByteOrder.html#t:ByteOrder
